// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlcgen

import (
	"context"
)

const createLocalAccount = `-- name: CreateLocalAccount :exec
INSERT INTO local_account (id, password_hash, enabled, oidc_subject, created_at, updated_at)
VALUES (1, '', 1, '', ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateLocalAccountParams struct {
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateLocalAccount(ctx context.Context, arg CreateLocalAccountParams) error {
	_, err := q.db.ExecContext(ctx, createLocalAccount, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const getLocalAccount = `-- name: GetLocalAccount :one
SELECT id, password_hash, enabled, oidc_subject, created_at, updated_at
FROM local_account
WHERE id = 1
`

func (q *Queries) GetLocalAccount(ctx context.Context) (LocalAccount, error) {
	row := q.db.QueryRowContext(ctx, getLocalAccount)
	var i LocalAccount
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Enabled,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLocalEnabled = `-- name: SetLocalEnabled :exec
UPDATE local_account SET enabled = ?, updated_at = ? WHERE id = 1
`

type SetLocalEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
}

func (q *Queries) SetLocalEnabled(ctx context.Context, arg SetLocalEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setLocalEnabled, arg.Enabled, arg.UpdatedAt)
	return err
}

const setLocalOIDCSubject = `-- name: SetLocalOIDCSubject :exec
UPDATE local_account SET oidc_subject = ?, updated_at = ? WHERE id = 1
`

type SetLocalOIDCSubjectParams struct {
	OidcSubject string
	UpdatedAt   int64
}

func (q *Queries) SetLocalOIDCSubject(ctx context.Context, arg SetLocalOIDCSubjectParams) error {
	_, err := q.db.ExecContext(ctx, setLocalOIDCSubject, arg.OidcSubject, arg.UpdatedAt)
	return err
}

const setLocalPassword = `-- name: SetLocalPassword :exec
UPDATE local_account SET password_hash = ?, updated_at = ? WHERE id = 1
`

type SetLocalPasswordParams struct {
	PasswordHash string
	UpdatedAt    int64
}

func (q *Queries) SetLocalPassword(ctx context.Context, arg SetLocalPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setLocalPassword, arg.PasswordHash, arg.UpdatedAt)
	return err
}
