// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlcgen

import (
	"context"
)

const blobExists = `-- name: BlobExists :one
SELECT EXISTS (SELECT 1 FROM blobs WHERE hash = ?)
`

func (q *Queries) BlobExists(ctx context.Context, hash string) (bool, error) {
	row := q.db.QueryRowContext(ctx, blobExists, hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBlobs = `-- name: CountBlobs :one
SELECT
  COUNT(*) AS blob_count,
  CAST(COALESCE(SUM(size), 0) AS INTEGER) AS uncompressed_bytes,
  CAST(COALESCE(SUM(LENGTH(content)), 0) AS INTEGER) AS stored_bytes
FROM blobs
`

type CountBlobsRow struct {
	BlobCount         int64
	UncompressedBytes int64
	StoredBytes       int64
}

// CAST is required: sqlc cannot infer a type for SUM/COALESCE on SQLite and
// emits interface{} without it.
func (q *Queries) CountBlobs(ctx context.Context) (CountBlobsRow, error) {
	row := q.db.QueryRowContext(ctx, countBlobs)
	var i CountBlobsRow
	err := row.Scan(&i.BlobCount, &i.UncompressedBytes, &i.StoredBytes)
	return i, err
}

const deleteUnreferencedBlobs = `-- name: DeleteUnreferencedBlobs :execrows
DELETE FROM blobs
WHERE hash NOT IN (SELECT compose_hash FROM snapshots)
  AND hash NOT IN (SELECT inspect_hash FROM service_states WHERE inspect_hash IS NOT NULL)
`

func (q *Queries) DeleteUnreferencedBlobs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedBlobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnreferencedEnvKeys = `-- name: DeleteUnreferencedEnvKeys :execrows
DELETE FROM env_keys
WHERE inspect_hash NOT IN (SELECT inspect_hash FROM service_states WHERE inspect_hash IS NOT NULL)
`

// Delete blobs no snapshot or service state references any more. Walking
// service_states.inspect_hash as well as snapshots.compose_hash is essential:
// inspect blobs are the majority of rows, and omitting them here would leak
// the entire store.
// env_keys are content-addressed too, so they orphan the same way blobs do.
func (q *Queries) DeleteUnreferencedEnvKeys(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedEnvKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBlob = `-- name: GetBlob :one
SELECT content FROM blobs WHERE hash = ?
`

func (q *Queries) GetBlob(ctx context.Context, hash string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getBlob, hash)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const putBlob = `-- name: PutBlob :exec
INSERT INTO blobs (hash, size, content, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (hash) DO NOTHING
`

type PutBlobParams struct {
	Hash      string
	Size      int64
	Content   []byte
	CreatedAt int64
}

func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.ExecContext(ctx, putBlob,
		arg.Hash,
		arg.Size,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
