// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countAudit = `-- name: CountAudit :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAudit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (ts, actor, method, action, ok, detail, remote)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	Ts     int64
	Actor  string
	Method string
	Action string
	Ok     int64
	Detail string
	Remote string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.Ts,
		arg.Actor,
		arg.Method,
		arg.Action,
		arg.Ok,
		arg.Detail,
		arg.Remote,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (host_id, project_id, service, ts, source, type, severity, actor, message, payload)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, host_id, project_id, service, ts, source, type, severity, actor, message, payload
`

type InsertEventParams struct {
	HostID    sql.NullInt64
	ProjectID sql.NullInt64
	Service   string
	Ts        int64
	Source    string
	Type      string
	Severity  string
	Actor     string
	Message   string
	Payload   string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.HostID,
		arg.ProjectID,
		arg.Service,
		arg.Ts,
		arg.Source,
		arg.Type,
		arg.Severity,
		arg.Actor,
		arg.Message,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProjectID,
		&i.Service,
		&i.Ts,
		&i.Source,
		&i.Type,
		&i.Severity,
		&i.Actor,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, ts, actor, method, "action", ok, detail, remote FROM audit_log
WHERE ts < ?1
ORDER BY ts DESC, id DESC
LIMIT ?2
`

type ListAuditParams struct {
	Before  int64
	MaxRows int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Method,
			&i.Action,
			&i.Ok,
			&i.Detail,
			&i.Remote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, host_id, project_id, service, ts, source, type, severity, actor, message, payload FROM events
WHERE ts >= ?1
  AND ts <= ?2
  AND (CAST(?3 AS INTEGER) = 0 OR project_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR service = ?4)
  AND (CAST(?5 AS TEXT) = '' OR type = ?5)
  AND (CAST(?6 AS TEXT) = '' OR severity = ?6)
ORDER BY ts DESC
LIMIT ?7
`

type ListEventsParams struct {
	FromTs    int64
	ToTs      int64
	ProjectID int64
	Service   string
	Type      string
	Severity  string
	MaxRows   int64
}

// Filters are optional: passing an empty string or 0 disables that clause,
// which keeps one query serving the whole /api/events surface.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.FromTs,
		arg.ToTs,
		arg.ProjectID,
		arg.Service,
		arg.Type,
		arg.Severity,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProjectID,
			&i.Service,
			&i.Ts,
			&i.Source,
			&i.Type,
			&i.Severity,
			&i.Actor,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAudit = `-- name: PruneAudit :execrows
DELETE FROM audit_log WHERE ts < ?1
`

func (q *Queries) PruneAudit(ctx context.Context, cutoff int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAudit, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
