// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (host_id, project_id, service, ts, source, type, severity, actor, message, payload)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, host_id, project_id, service, ts, source, type, severity, actor, message, payload
`

type InsertEventParams struct {
	HostID    sql.NullInt64
	ProjectID sql.NullInt64
	Service   string
	Ts        int64
	Source    string
	Type      string
	Severity  string
	Actor     string
	Message   string
	Payload   string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.HostID,
		arg.ProjectID,
		arg.Service,
		arg.Ts,
		arg.Source,
		arg.Type,
		arg.Severity,
		arg.Actor,
		arg.Message,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProjectID,
		&i.Service,
		&i.Ts,
		&i.Source,
		&i.Type,
		&i.Severity,
		&i.Actor,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, host_id, project_id, service, ts, source, type, severity, actor, message, payload FROM events
WHERE ts >= ?1
  AND ts <= ?2
  AND (CAST(?3 AS INTEGER) = 0 OR project_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR service = ?4)
  AND (CAST(?5 AS TEXT) = '' OR type = ?5)
  AND (CAST(?6 AS TEXT) = '' OR severity = ?6)
ORDER BY ts DESC
LIMIT ?7
`

type ListEventsParams struct {
	FromTs    int64
	ToTs      int64
	ProjectID int64
	Service   string
	Type      string
	Severity  string
	MaxRows   int64
}

// Filters are optional: passing an empty string or 0 disables that clause,
// which keeps one query serving the whole /api/events surface.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.FromTs,
		arg.ToTs,
		arg.ProjectID,
		arg.Service,
		arg.Type,
		arg.Severity,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProjectID,
			&i.Service,
			&i.Ts,
			&i.Source,
			&i.Type,
			&i.Severity,
			&i.Actor,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
