// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countComposeFiles = `-- name: CountComposeFiles :one
SELECT COUNT(*) FROM compose_files
`

// Delete compose file rows whose blob nothing else references. Handled by the
// snapshot cascade, so this exists only for the GC pass to reason about.
func (q *Queries) CountComposeFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComposeFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOpposingRule = `-- name: DeleteOpposingRule :execrows
DELETE FROM redaction_rules
WHERE project_id = ? AND path = ? AND kind = ? AND key = ? AND line_no = ? AND action != ?
`

type DeleteOpposingRuleParams struct {
	ProjectID int64
	Path      string
	Kind      string
	Key       string
	LineNo    int64
	Action    string
}

// Toggling a line replaces any opposing rule for the same target, so a line
// cannot end up both hidden and revealed.
func (q *Queries) DeleteOpposingRule(ctx context.Context, arg DeleteOpposingRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOpposingRule,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.Key,
		arg.LineNo,
		arg.Action,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRedactionRule = `-- name: DeleteRedactionRule :execrows
DELETE FROM redaction_rules WHERE id = ? AND project_id = ?
`

type DeleteRedactionRuleParams struct {
	ID        int64
	ProjectID int64
}

func (q *Queries) DeleteRedactionRule(ctx context.Context, arg DeleteRedactionRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRedactionRule, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComposeFile = `-- name: GetComposeFile :one
SELECT snapshot_id, path, content_hash, line_count, size, status FROM compose_files WHERE snapshot_id = ? AND path = ?
`

type GetComposeFileParams struct {
	SnapshotID int64
	Path       string
}

func (q *Queries) GetComposeFile(ctx context.Context, arg GetComposeFileParams) (ComposeFile, error) {
	row := q.db.QueryRowContext(ctx, getComposeFile, arg.SnapshotID, arg.Path)
	var i ComposeFile
	err := row.Scan(
		&i.SnapshotID,
		&i.Path,
		&i.ContentHash,
		&i.LineCount,
		&i.Size,
		&i.Status,
	)
	return i, err
}

const insertComposeFile = `-- name: InsertComposeFile :exec
INSERT INTO compose_files (snapshot_id, path, content_hash, line_count, size, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertComposeFileParams struct {
	SnapshotID  int64
	Path        string
	ContentHash sql.NullString
	LineCount   int64
	Size        int64
	Status      string
}

func (q *Queries) InsertComposeFile(ctx context.Context, arg InsertComposeFileParams) error {
	_, err := q.db.ExecContext(ctx, insertComposeFile,
		arg.SnapshotID,
		arg.Path,
		arg.ContentHash,
		arg.LineCount,
		arg.Size,
		arg.Status,
	)
	return err
}

const insertRedactionRule = `-- name: InsertRedactionRule :one
INSERT INTO redaction_rules (project_id, path, action, kind, key, line_no, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, path, action, kind, key, line_no) DO UPDATE SET note = excluded.note
RETURNING id, project_id, path, "action", kind, "key", line_no, note, created_at
`

type InsertRedactionRuleParams struct {
	ProjectID int64
	Path      string
	Action    string
	Kind      string
	Key       string
	LineNo    int64
	Note      string
	CreatedAt int64
}

func (q *Queries) InsertRedactionRule(ctx context.Context, arg InsertRedactionRuleParams) (RedactionRule, error) {
	row := q.db.QueryRowContext(ctx, insertRedactionRule,
		arg.ProjectID,
		arg.Path,
		arg.Action,
		arg.Kind,
		arg.Key,
		arg.LineNo,
		arg.Note,
		arg.CreatedAt,
	)
	var i RedactionRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Action,
		&i.Kind,
		&i.Key,
		&i.LineNo,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listComposeFiles = `-- name: ListComposeFiles :many
SELECT snapshot_id, path, content_hash, line_count, size, status FROM compose_files WHERE snapshot_id = ? ORDER BY path
`

func (q *Queries) ListComposeFiles(ctx context.Context, snapshotID int64) ([]ComposeFile, error) {
	rows, err := q.db.QueryContext(ctx, listComposeFiles, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposeFile{}
	for rows.Next() {
		var i ComposeFile
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Path,
			&i.ContentHash,
			&i.LineCount,
			&i.Size,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedactionRules = `-- name: ListRedactionRules :many
SELECT id, project_id, path, "action", kind, "key", line_no, note, created_at FROM redaction_rules WHERE project_id = ? ORDER BY path, kind, key, line_no
`

func (q *Queries) ListRedactionRules(ctx context.Context, projectID int64) ([]RedactionRule, error) {
	rows, err := q.db.QueryContext(ctx, listRedactionRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RedactionRule{}
	for rows.Next() {
		var i RedactionRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Action,
			&i.Kind,
			&i.Key,
			&i.LineNo,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectFilePaths = `-- name: ProjectFilePaths :many
SELECT DISTINCT compose_files.path
FROM compose_files
JOIN snapshots ON snapshots.id = compose_files.snapshot_id
WHERE snapshots.project_id = ?
ORDER BY compose_files.path
`

// Every distinct path a project has ever had a file at, newest first, so the
// UI can offer a file even if the latest snapshot could not read it.
func (q *Queries) ProjectFilePaths(ctx context.Context, projectID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, projectFilePaths, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
