// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const listHosts = `-- name: ListHosts :many
SELECT id, name, endpoint, docker_version, last_seen_at, created_at FROM hosts ORDER BY name
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.DockerVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHost = `-- name: UpsertHost :one
INSERT INTO hosts (name, endpoint, docker_version, last_seen_at, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
  endpoint = excluded.endpoint,
  docker_version = excluded.docker_version,
  last_seen_at = excluded.last_seen_at
RETURNING id, name, endpoint, docker_version, last_seen_at, created_at
`

type UpsertHostParams struct {
	Name          string
	Endpoint      string
	DockerVersion sql.NullString
	LastSeenAt    sql.NullInt64
	CreatedAt     int64
}

func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, upsertHost,
		arg.Name,
		arg.Endpoint,
		arg.DockerVersion,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.DockerVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
