// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Blob struct {
	Hash      string
	Size      int64
	Content   []byte
	CreatedAt int64
}

type ComposeFile struct {
	SnapshotID  int64
	Path        string
	ContentHash sql.NullString
	LineCount   int64
	Size        int64
	Status      string
}

type EnvKey struct {
	InspectHash    string
	Key            string
	ValueHmac      string
	ValueLenBucket string
	Redacted       int64
	Value          sql.NullString
}

type Event struct {
	ID        int64
	HostID    sql.NullInt64
	ProjectID sql.NullInt64
	Service   string
	Ts        int64
	Source    string
	Type      string
	Severity  string
	Actor     string
	Message   string
	Payload   string
}

type Host struct {
	ID            int64
	Name          string
	Endpoint      string
	DockerVersion sql.NullString
	LastSeenAt    sql.NullInt64
	CreatedAt     int64
}

type LocalAccount struct {
	ID           int64
	PasswordHash string
	Enabled      int64
	OidcSubject  string
	CreatedAt    int64
	UpdatedAt    int64
}

type Project struct {
	ID          int64
	HostID      int64
	Name        string
	WorkingDir  string
	ConfigFiles string
	FirstSeenAt int64
	LastSeenAt  int64
	Archived    int64
}

type RedactionRule struct {
	ID        int64
	ProjectID int64
	Path      string
	Action    string
	Kind      string
	Key       string
	LineNo    int64
	Note      string
	CreatedAt int64
}

type ServiceState struct {
	ID             int64
	SnapshotID     int64
	Service        string
	ContainerID    string
	ContainerName  string
	ImageRef       string
	ImageID        string
	ImageDigest    string
	ImageCreatedAt *int64
	State          string
	Health         string
	RestartCount   int64
	StartedAt      *int64
	InspectHash    sql.NullString
}

type Session struct {
	TokenHash  string
	Subject    string
	Name       string
	Method     string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
}

type Setting struct {
	Key   string
	Value string
}

type Snapshot struct {
	ID                 int64
	ProjectID          int64
	TakenAt            int64
	Trigger            string
	ComposeHash        string
	ComposeSource      string
	ConfigFingerprint  string
	RuntimeFingerprint string
	ConfigChanged      int64
	RuntimeChanged     int64
	LastObservedAt     int64
	ObservationCount   int64
	FilesFingerprint   string
	FilesChanged       int64
}
