// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
)

const getProject = `-- name: GetProject :one
SELECT id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.WorkingDir,
		&i.ConfigFiles,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Archived,
	)
	return i, err
}

const getProjectIDByName = `-- name: GetProjectIDByName :one
SELECT p.id, p.host_id FROM projects p
JOIN hosts h ON h.id = p.host_id
WHERE p.name = ?
ORDER BY p.id
LIMIT 1
`

type GetProjectIDByNameRow struct {
	ID     int64
	HostID int64
}

// Resolves a compose project name to its id and its host's, for the event path.
//
// Names are unique per host and Silt records one host, so the first match is
// the answer. Served by the UNIQUE (host_id, name) index; the alternative was
// listing every host and every project on every Docker event, which on a
// forty-project host during a `compose up` is a table scan per event.
//
// The host comes back too because the join was already here. Nothing had ever
// set events.host_id: the column, the EventRecord field and the write path all
// existed and no caller filled any of them, so every event in every Silt
// database had a null host. One more column on a query that was already
// joining the table is what it cost to make it true.
//
// No em dashes in this file, and no other non-ASCII either. sqlc truncates the
// end of a query by one byte for every multi-byte character in its comment, so
// this comment with its original dash in it generated "LIMIT" with the 1 gone
// and every event silently stopped finding its project. See
// TestQueryFilesAreASCII.
func (q *Queries) GetProjectIDByName(ctx context.Context, name string) (GetProjectIDByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectIDByName, name)
	var i GetProjectIDByNameRow
	err := row.Scan(&i.ID, &i.HostID)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived FROM projects WHERE host_id = ? ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, hostID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.WorkingDir,
			&i.ConfigFiles,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (host_id, name, working_dir, config_files, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (host_id, name) DO UPDATE SET
  working_dir = excluded.working_dir,
  config_files = excluded.config_files,
  last_seen_at = excluded.last_seen_at,
  archived = 0
RETURNING id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived
`

type UpsertProjectParams struct {
	HostID      int64
	Name        string
	WorkingDir  string
	ConfigFiles string
	FirstSeenAt int64
	LastSeenAt  int64
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.HostID,
		arg.Name,
		arg.WorkingDir,
		arg.ConfigFiles,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.WorkingDir,
		&i.ConfigFiles,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Archived,
	)
	return i, err
}
