// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
)

const getProject = `-- name: GetProject :one
SELECT id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.WorkingDir,
		&i.ConfigFiles,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Archived,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived FROM projects WHERE host_id = ? ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, hostID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.WorkingDir,
			&i.ConfigFiles,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (host_id, name, working_dir, config_files, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (host_id, name) DO UPDATE SET
  working_dir = excluded.working_dir,
  config_files = excluded.config_files,
  last_seen_at = excluded.last_seen_at,
  archived = 0
RETURNING id, host_id, name, working_dir, config_files, first_seen_at, last_seen_at, archived
`

type UpsertProjectParams struct {
	HostID      int64
	Name        string
	WorkingDir  string
	ConfigFiles string
	FirstSeenAt int64
	LastSeenAt  int64
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.HostID,
		arg.Name,
		arg.WorkingDir,
		arg.ConfigFiles,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.WorkingDir,
		&i.ConfigFiles,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Archived,
	)
	return i, err
}
