// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlcgen

import (
	"context"
)

const pruneChangedSnapshots = `-- name: PruneChangedSnapshots :execrows
DELETE FROM snapshots
WHERE snapshots.taken_at < ?
  AND EXISTS (
    SELECT 1 FROM snapshots AS older
    WHERE older.project_id = snapshots.project_id
      AND older.taken_at < snapshots.taken_at
  )
`

func (q *Queries) PruneChangedSnapshots(ctx context.Context, takenAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneChangedSnapshots, takenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events WHERE ts < ?
`

func (q *Queries) PruneEvents(ctx context.Context, ts int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneUnchangedSnapshots = `-- name: PruneUnchangedSnapshots :execrows
DELETE FROM snapshots
WHERE snapshots.config_changed = 0
  AND snapshots.taken_at < ?
  AND EXISTS (
    SELECT 1 FROM snapshots AS older
    WHERE older.project_id = snapshots.project_id
      AND older.taken_at < snapshots.taken_at
  )
`

// Unchanged snapshots are proof-of-liveness and prune aggressively. The
// oldest surviving snapshot for a project is never pruned: it is the base for
// the earliest diff the UI can offer.
func (q *Queries) PruneUnchangedSnapshots(ctx context.Context, takenAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneUnchangedSnapshots, takenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
