// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, subject, name, method, created_at, last_seen_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash  string
	Subject    string
	Name       string
	Method     string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.Subject,
		arg.Name,
		arg.Method,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ? OR last_seen_at <= ?
`

type DeleteExpiredSessionsParams struct {
	ExpiresAt  int64
	LastSeenAt int64
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, arg.ExpiresAt, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForSubject = `-- name: DeleteSessionsForSubject :execrows
DELETE FROM sessions WHERE subject = ?
`

func (q *Queries) DeleteSessionsForSubject(ctx context.Context, subject string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsForSubject, subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT token_hash, subject, name, method, created_at, last_seen_at, expires_at
FROM sessions
WHERE token_hash = ?
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.Subject,
		&i.Name,
		&i.Method,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE token_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt int64
	TokenHash  string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.TokenHash)
	return err
}
