// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting, arg.Key, arg.Value)
	return err
}
