// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countSnapshots = `-- name: CountSnapshots :one
SELECT COUNT(*) FROM snapshots WHERE project_id = ?
`

func (q *Queries) CountSnapshots(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSnapshots, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count FROM snapshots WHERE id = ?
`

func (q *Queries) GetSnapshot(ctx context.Context, id int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TakenAt,
		&i.Trigger,
		&i.ComposeHash,
		&i.ComposeSource,
		&i.ConfigFingerprint,
		&i.RuntimeFingerprint,
		&i.ConfigChanged,
		&i.RuntimeChanged,
		&i.LastObservedAt,
		&i.ObservationCount,
	)
	return i, err
}

const insertEnvKey = `-- name: InsertEnvKey :exec
INSERT INTO env_keys (inspect_hash, key, value_hmac, value_len_bucket, redacted, value)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (inspect_hash, key) DO NOTHING
`

type InsertEnvKeyParams struct {
	InspectHash    string
	Key            string
	ValueHmac      string
	ValueLenBucket string
	Redacted       int64
	Value          sql.NullString
}

func (q *Queries) InsertEnvKey(ctx context.Context, arg InsertEnvKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertEnvKey,
		arg.InspectHash,
		arg.Key,
		arg.ValueHmac,
		arg.ValueLenBucket,
		arg.Redacted,
		arg.Value,
	)
	return err
}

const insertServiceState = `-- name: InsertServiceState :exec
INSERT INTO service_states (
  snapshot_id, service, container_id, container_name, image_ref, image_id,
  image_digest, image_created_at, state, health, restart_count, started_at, inspect_hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertServiceStateParams struct {
	SnapshotID     int64
	Service        string
	ContainerID    string
	ContainerName  string
	ImageRef       string
	ImageID        string
	ImageDigest    string
	ImageCreatedAt *int64
	State          string
	Health         string
	RestartCount   int64
	StartedAt      *int64
	InspectHash    sql.NullString
}

func (q *Queries) InsertServiceState(ctx context.Context, arg InsertServiceStateParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceState,
		arg.SnapshotID,
		arg.Service,
		arg.ContainerID,
		arg.ContainerName,
		arg.ImageRef,
		arg.ImageID,
		arg.ImageDigest,
		arg.ImageCreatedAt,
		arg.State,
		arg.Health,
		arg.RestartCount,
		arg.StartedAt,
		arg.InspectHash,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :one
INSERT INTO snapshots (
  project_id, taken_at, trigger, compose_hash, compose_source,
  config_fingerprint, runtime_fingerprint, config_changed, runtime_changed,
  last_observed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count
`

type InsertSnapshotParams struct {
	ProjectID          int64
	TakenAt            int64
	Trigger            string
	ComposeHash        string
	ComposeSource      string
	ConfigFingerprint  string
	RuntimeFingerprint string
	ConfigChanged      int64
	RuntimeChanged     int64
	LastObservedAt     int64
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, insertSnapshot,
		arg.ProjectID,
		arg.TakenAt,
		arg.Trigger,
		arg.ComposeHash,
		arg.ComposeSource,
		arg.ConfigFingerprint,
		arg.RuntimeFingerprint,
		arg.ConfigChanged,
		arg.RuntimeChanged,
		arg.LastObservedAt,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TakenAt,
		&i.Trigger,
		&i.ComposeHash,
		&i.ComposeSource,
		&i.ConfigFingerprint,
		&i.RuntimeFingerprint,
		&i.ConfigChanged,
		&i.RuntimeChanged,
		&i.LastObservedAt,
		&i.ObservationCount,
	)
	return i, err
}

const latestChangedSnapshotsBefore = `-- name: LatestChangedSnapshotsBefore :many
SELECT id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count FROM snapshots
WHERE project_id = ?1
  AND taken_at < ?2
  AND config_changed = 1
ORDER BY taken_at DESC
LIMIT ?3
`

type LatestChangedSnapshotsBeforeParams struct {
	ProjectID int64
	Before    int64
	MaxRows   int64
}

func (q *Queries) LatestChangedSnapshotsBefore(ctx context.Context, arg LatestChangedSnapshotsBeforeParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, latestChangedSnapshotsBefore, arg.ProjectID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TakenAt,
			&i.Trigger,
			&i.ComposeHash,
			&i.ComposeSource,
			&i.ConfigFingerprint,
			&i.RuntimeFingerprint,
			&i.ConfigChanged,
			&i.RuntimeChanged,
			&i.LastObservedAt,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestSnapshot = `-- name: LatestSnapshot :one
SELECT id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count FROM snapshots WHERE project_id = ? ORDER BY taken_at DESC LIMIT 1
`

func (q *Queries) LatestSnapshot(ctx context.Context, projectID int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, latestSnapshot, projectID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TakenAt,
		&i.Trigger,
		&i.ComposeHash,
		&i.ComposeSource,
		&i.ConfigFingerprint,
		&i.RuntimeFingerprint,
		&i.ConfigChanged,
		&i.RuntimeChanged,
		&i.LastObservedAt,
		&i.ObservationCount,
	)
	return i, err
}

const listEnvKeys = `-- name: ListEnvKeys :many
SELECT env_keys.inspect_hash, env_keys."key", env_keys.value_hmac, env_keys.value_len_bucket, env_keys.redacted, env_keys.value FROM env_keys
JOIN service_states ON service_states.inspect_hash = env_keys.inspect_hash
WHERE service_states.snapshot_id = ?
ORDER BY service_states.service, env_keys.key
`

func (q *Queries) ListEnvKeys(ctx context.Context, snapshotID int64) ([]EnvKey, error) {
	rows, err := q.db.QueryContext(ctx, listEnvKeys, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvKey{}
	for rows.Next() {
		var i EnvKey
		if err := rows.Scan(
			&i.InspectHash,
			&i.Key,
			&i.ValueHmac,
			&i.ValueLenBucket,
			&i.Redacted,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceStates = `-- name: ListServiceStates :many
SELECT id, snapshot_id, service, container_id, container_name, image_ref, image_id, image_digest, image_created_at, state, health, restart_count, started_at, inspect_hash FROM service_states WHERE snapshot_id = ? ORDER BY service
`

func (q *Queries) ListServiceStates(ctx context.Context, snapshotID int64) ([]ServiceState, error) {
	rows, err := q.db.QueryContext(ctx, listServiceStates, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceState{}
	for rows.Next() {
		var i ServiceState
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Service,
			&i.ContainerID,
			&i.ContainerName,
			&i.ImageRef,
			&i.ImageID,
			&i.ImageDigest,
			&i.ImageCreatedAt,
			&i.State,
			&i.Health,
			&i.RestartCount,
			&i.StartedAt,
			&i.InspectHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count FROM snapshots
WHERE project_id = ?1
  AND taken_at < ?2
  AND (CAST(?3 AS INTEGER) = 0 OR config_changed = 1)
ORDER BY taken_at DESC
LIMIT ?4
`

type ListSnapshotsParams struct {
	ProjectID   int64
	Before      int64
	ChangedOnly int64
	MaxRows     int64
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots,
		arg.ProjectID,
		arg.Before,
		arg.ChangedOnly,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TakenAt,
			&i.Trigger,
			&i.ComposeHash,
			&i.ComposeSource,
			&i.ConfigFingerprint,
			&i.RuntimeFingerprint,
			&i.ConfigChanged,
			&i.RuntimeChanged,
			&i.LastObservedAt,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectForService = `-- name: ProjectForService :one
SELECT snapshots.project_id FROM service_states
JOIN snapshots ON snapshots.id = service_states.snapshot_id
WHERE service_states.service = ?
ORDER BY snapshots.taken_at DESC
LIMIT 1
`

// Resolve a service name to the project it most recently belonged to, so an
// external monitor named after a service still lands on the right project.
func (q *Queries) ProjectForService(ctx context.Context, service string) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectForService, service)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const snapshotsInRange = `-- name: SnapshotsInRange :many
SELECT id, project_id, taken_at, "trigger", compose_hash, compose_source, config_fingerprint, runtime_fingerprint, config_changed, runtime_changed, last_observed_at, observation_count FROM snapshots
WHERE taken_at >= ?1
  AND taken_at <= ?2
  AND (CAST(?3 AS INTEGER) = 0 OR project_id = ?3)
ORDER BY taken_at DESC
LIMIT ?4
`

type SnapshotsInRangeParams struct {
	FromTs    int64
	ToTs      int64
	ProjectID int64
	MaxRows   int64
}

func (q *Queries) SnapshotsInRange(ctx context.Context, arg SnapshotsInRangeParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, snapshotsInRange,
		arg.FromTs,
		arg.ToTs,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TakenAt,
			&i.Trigger,
			&i.ComposeHash,
			&i.ComposeSource,
			&i.ConfigFingerprint,
			&i.RuntimeFingerprint,
			&i.ConfigChanged,
			&i.RuntimeChanged,
			&i.LastObservedAt,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSnapshot = `-- name: TouchSnapshot :exec
UPDATE snapshots
SET last_observed_at = ?, observation_count = observation_count + 1
WHERE id = ?
`

type TouchSnapshotParams struct {
	LastObservedAt int64
	ID             int64
}

// An observation identical to the previous snapshot records that it is still
// current, rather than inserting hundreds of duplicate child rows.
func (q *Queries) TouchSnapshot(ctx context.Context, arg TouchSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, touchSnapshot, arg.LastObservedAt, arg.ID)
	return err
}
